Feature rating events
GlazyrinAV/java-explore-with-me pull request #6
Opened 2023-08-31 14:23 UTC by GlazyrinAV

2023-09-01 10:58 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.

Вопрос только один, а не получится ли сортировку перетащить на уровень СУБД? :)

2023-09-01 10:58 UTC, EugeneLenkevich commented on ewm/ewm-service/src/main/java/ru/practicum/ewmservice/model/Mark.java
> +
Пустую строчечку бы тут убрать :)

2023-09-01 10:58 UTC, EugeneLenkevich commented on ewm/ewm-service/src/main/java/ru/practicum/ewmservice/service/event/EventPublicServiceImpl.java
> +                result.sort(Comparator.comparing(EventDto::getEventDate).reversed());
Вот тут не совсем понятно, а не получится все же сделать сортировку на стороне СУБД?
У нас сортировка работает только для тех записей, что попали на страницу с from по to, в общем случае записи могут храниться как попало, допустим если в таблицу пишут несколько объектов, какой то из них подвис не время (например блокировку словил, такое часто бывает), а потом вывалил все записи уже через какое то время.  В общем очень это ненадежно так сортировать :)

2023-09-01 10:58 UTC, EugeneLenkevich commented on ewm/ewm-service/src/main/java/ru/practicum/ewmservice/repository/EventRepository.java
> +    @Query("SELECT E FROM Event AS E left JOIN Mark AS M ON M.event.id = E.id " +
На счет джоинов в JPQL, а их же можно немного проще записать, без указанию ключей в ON, примерно вот так

![image](https://github.com/GlazyrinAV/java-explore-with-me/assets/109306643/f3ec3a42-da29-4f53-bc42-f582eb30c68a)

Единственное надо дописать связи в табличке Event

2023-09-01 11:52 UTC, GlazyrinAV commented on ewm/ewm-service/src/main/java/ru/practicum/ewmservice/repository/EventRepository.java
> +    @Query("SELECT E FROM Event AS E left JOIN Mark AS M ON M.event.id = E.id " +
Да, сейчас попробую реализовать. Вопрос только с сортировкой по Views. Согласно ТЗ - необходимо указывать количество уникальных по IP просмотров. Для этого обращаюсь к серверу Stats. Если я правильно понимаю, в этом случае сортировку по Views все равно придется делать в методе сервиса, т.к. адекватного способа заджойнить таблицу из  бд с другого сервера пока не нашел.

2023-09-01 12:18 UTC, EugeneLenkevich commented on ewm/ewm-service/src/main/java/ru/practicum/ewmservice/repository/EventRepository.java
> +    @Query("SELECT E FROM Event AS E left JOIN Mark AS M ON M.event.id = E.id " +
Ну да, все верно, если тянуть данные с другого сервиса, то сортировать придется в коде.

PS
Вообще, способ есть - мы можем в бэкграунде синхронизировать БД наших сервисов, периодически подливать нужные данные для отчета( например через кафку), но это явно за рамками курса :)

2023-09-02 14:21 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-03 18:52 UTC, merged